version: "2.1"

services:
  grpc-server-db:
    container_name: grpc-server-db
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567
    ports:
      - 5430:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/grpc-server-db:/var/lib/postgresql/data